import { Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner"


const inter = Inter({subsets:["latin"]});
// console.log(inter);
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className= {`${inter.className}`}
      >
      <Header></Header>
      <main className="min-h-screen mt-[4rem]">
        {children}
      </main>
      <Toaster richColors />
      
      <footer className=" py-12 bg-blue-300" >
      <div className="container text-center mx-auto text-gray-950 "> 
        made with 😍 by blazeboy
      </div>
      
      </footer>
      </body>
    </html>
    </ClerkProvider>
 
  );
}
